## Implementing Basis of tensorflow

In [1]:
import tensorflow as tf

In [2]:
## constant to create and tensorflow tensor
tf.constant(2)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

By default the dtype of the tensorflow is 32 bit because it is far more than enough fro neural network weights

In [3]:
### building and tensor of ndarray
tf.constant([1,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [4]:
### shape of tensor
tf.constant([1,2,3]).shape

TensorShape([3])

In [10]:
### similar operations as numpy
t = tf.constant([[1.,2.,3.],[4.,5.,6.]])
print("tensor: \n",t)
print("---"*10)
print("Square of tensor: \n",tf.square(t))
print(f"Scaling in tensorflow: \n{t+10}")

tensor: 
 tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
------------------------------
Square of tensor: 
 tf.Tensor(
[[ 1.  4.  9.]
 [16. 25. 36.]], shape=(2, 3), dtype=float32)
Scaling in tensorflow: 
[[11. 12. 13.]
 [14. 15. 16.]]


In [11]:
t[:,:]

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [14]:
t[:,-1] ## all row last columns

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3., 6.], dtype=float32)>

In [16]:
t[0,0]

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [19]:
## tranpose in tensor : it not only transpose but also create the tensor
x = tf.transpose(t)
x

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 4.],
       [2., 5.],
       [3., 6.]], dtype=float32)>

In [25]:
### example 
import numpy as np
n = np.array([[1.,2.,3.],[4.,5.,6.]])
x = n.T
print(x)

[[1. 4.]
 [2. 5.]
 [3. 6.]]


In [26]:
## casting to other type 
t1 = tf.constant(4.0,dtype=tf.float64) ## 64 bit 
t2 = tf.constant(4.0) ## default 32 bit

##### error: tf.add(t1,t2)
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
Cell In[27], line 1
----> 1 tf.add(t1,t2)

File ~\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\weak_tensor_ops.py:142, in weak_tensor_binary_op_wrapper.<locals>.wrapper(*args, **kwargs)
    140 def wrapper(*args, **kwargs):
    141   if not ops.is_auto_dtype_conversion_enabled():
--> 142     return op(*args, **kwargs)
    143   bound_arguments = signature.bind(*args, **kwargs)
    144   bound_arguments.apply_defaults()

File ~\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\util\traceback_utils.py:153, in filter_traceback.<locals>.error_handler(*args, **kwargs)
    151 except Exception as e:
    152   filtered_tb = _process_traceback_frames(e.__traceback__)
--> 153   raise e.with_traceback(filtered_tb) from None
    154 finally:
    155   del filtered_tb

File ~\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\framework\ops.py:6027, in raise_from_not_ok_status(e, name)
   6025 def raise_from_not_ok_status(e, name) -> NoReturn:
   6026   e.message += (" name: " + str(name if name is not None else ""))
-> 6027   raise core._status_to_exception(e) from None

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a double tensor but is a float tensor [Op:AddV2] name: 

In [28]:
tf.add(t2,tf.cast(t1,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

# Since the tensorflow tensors are not mutable 
### example
t = tf.constant(4.)
tf.assign(t,10.)
## deperacted from version1

In [35]:
x = tf.Variable([1,2,3])
x[0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [36]:
x[0].assign(2*x[0])

<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([2, 2, 3], dtype=int32)>

# This is okay for start 
### now go to custom implementaion of layers,activations,losses,metrics,blocks,etc